### ISSUE TITLE
startupScriptContent does not seem to run when installing helm chart

### ISSUE THREAD

**Issue by hop-along-polly** [localstack/helm-charts#100]
I'm trying to install Localstack along side a custom application using Helm. A part of my deployment is making sure an S3 bucket exists in LocalStack ahead of time. I thought `startupScriptContent` would have been the correct parameter to use but it seems as if that script is never executed. The bucket is not created, and I don't see any logs indicating the script encountered an error or even tried to run.

I don't think having the Localstack chart as a subchart would really effect this but I figured it's worth mentioning my setup.

Here is the directory structure.
```
charts/
    myapp.0.1.0.tgz
   localstack-0.6.5.tgz
Chart.yaml
values.yaml
```

The contents of `Chart.yaml`
```
apiVersion: v2
description: a custom app deployed alongside localstack
engine: gotpl
name: my-custom-app
version: 0.1.2
dependencies:
- name: my-custom-service
  alias: myapp
  version: 0.1.0
  repository: file://charts/myapp
- name: localstack
  alias: s3
  version: 0.6.5
  repository: https://localstack.github.io/helm-charts
```

The contents of my `values.yaml` file
```
localstack:
  startServices: s3
  enableStartupScripts: true
  startupScriptContent: |
    !#/bin/sh
    awslocal s3 mb s3://hl-modelscan
```

When I run `helm install myapp .` everything deploys w/o and error but the bucket is not there.

Here's a sample of the logs for the localstack pod just after deloyment.
```
LocalStack version: 3.0.1.dev
LocalStack build date: 2023-11-17
LocalStack build git hash: 32a7946f

2023-11-19T18:58:05.994  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-11-19T18:58:05.994  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-11-19T18:58:06.028  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 603.21ms
Ready.
2023-11-19T18:58:54.093  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.ListBuckets => 200
```

If there's any other information I need to provide please let me know and I'm happy to do so.

**Comment by alexrashed** [comment]
Hi @hop-along-polly!
I haven't tested it when being used as a sub-chart, but using the following values and command works perfectly fine:
```bash
$ cat test-values.yaml
debug: true
startServices: s3
enableStartupScripts: true
startupScriptContent: |
  #!/bin/bash
  awslocal s3 mb s3://hl-modelscan
$ helm install ls-helm-demo localstack/localstack -f test-values.yaml
...
$ kubectl logs -f ls-helm-demo-localstack-5b7bdbdf5b-24r8f
...
2023-11-20T13:05:59.021 DEBUG --- [  MainThread] localstack.runtime.init    : Running READY script /etc/localstack/init/ready.d/ls-helm-demo-localstack-init-scripts-config.sh
2023-11-20T13:05:59.584  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.CreateBucket => 200
make_bucket: hl-modelscan
...
```

It seems like your shebang is wrong (it has to be `#!...`, not `!#...`).
If this does not solve your problems, please check if your subchart config is working well.
If this still does not solve your issues, please post the rendered deployment here: `kubectl get deployment -o json <localstack-deployment-name>`

Thanks!

**Comment by hop-along-polly** [comment]
I figured it out. In my `Chart.yaml` file I was creating an alias for `localstack` but in my `values.yaml` I was using `localstack` instead of the alias.

```bash
# Chart.yaml
apiVersion: v2
description: a custom app deployed alongside localstack
engine: gotpl
name: my-custom-app
version: 0.1.2
dependencies:
- name: my-custom-service
  alias: myapp
  version: 0.1.0
  repository: file://charts/myapp
- name: localstack
  alias: s3  # <- Since I alias "localstack" to "s3" I need to use "s3" in my values file instead of "localstack"
  version: 0.6.5
  repository: https://localstack.github.io/helm-charts
```

Here is the corrected `values.yaml` file
```bash
s3: # <- This needed to be s3 instead of localstack
  startServices: s3
  enableStartupScripts: true
  startupScriptContent: |
    #!/bin/sh
    awslocal s3 mb s3://hl-modelscan
```
