### ISSUE TITLE
add support for ingressClassName

### ISSUE THREAD

**Issue by arnoldas-jakstas-tg** [localstack/helm-charts#114]
For Kubernetes >= 1.18 we should be able to specify the ingress-controller via the field ingressClassName

See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress

Thanks.

**Comment by alexrashed** [comment]
Hey @arnoldas-jakstas-tg!
Thanks for the suggestion, this is something we could easily implement. In fact, this would be a good first issue, would you be interested in filing a PR?

**Comment by paperbag-zz** [comment]
> Hey @arnoldas-jakstas-tg! Thanks for the suggestion, this is something we could easily implement. In fact, this would be a good first issue, would you be interested in filing a PR?

Sure, I'll raise a PR for the change.
