### ISSUE TITLE
Error in the generate template - ContainerPort

### ISSUE THREAD

**Issue by freddy-mesa** [localstack/helm-charts#18]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
The generate yaml using *helm template localstack/localstack* has a error in Deployment.spec.template.spec.containers[0].ports[0]. In Port session, has a "container" token but suppose to be "containerPort".
...

## Expected behavior
Helm package installed ..
...

## Actual behavior
```
Helm release localstack not installed. Installing...
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): unknown field "container" in io.k8s.api.core.v1.ContainerPort, ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort]
```
...

# Steps to reproduce
```shell
helm repo add localstack https://localstack.github.io/helm-charts
helm repo update
skaffold run
```

## Command used to start LocalStack
skaffold run
...

## Helm Chart Version
NAME: localstack/localstack                 	
CHART VERSION: 0.1.3	
APP VERSION: latest (v0.12.7)

**Comment by sv3ndk** [comment]
As I understand it, a fix of this issue is currently being discussed here: https://github.com/localstack/helm-charts/pull/16

**Comment by freddy-mesa** [comment]
Excellent waiting for been merge!!!
