### ISSUE TITLE
https://localstack.github.io/helm-charts is not accessible

### ISSUE THREAD

**Issue by depohmel** [localstack/helm-charts#22]
Hello, everything was working just fine until today's morning (06/14/2021) 
looks like cart url is not accessible any more. 

Could someone please take a look?

**Comment by whummer** [comment]
Thanks for reporting @depohmel . We were facing a slight issue with our DNS setup today, apologies for the inconvenience. 

The DNS name `helm.localstack.cloud` should now be properly restored - please note that it may take up to 10-15mins for the DNS changes to propagate. 

Please report here if the problem still persists. Thanks!

**Comment by depohmel** [comment]
Thanks a lot. It works now!!!
