### ISSUE TITLE
Ingress using the wrong api

### ISSUE THREAD

**Issue by miaucl** [localstack/helm-charts#30]
I am trying to set up the localstack `s3` service with an ingress. On a clean installation, I run into following problem:

_(v0.2.3)_
```bash
helm install localstack-test localstack-charts/localstack --set startServices=s3 --set ingress.enabled=true
>> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

_(v0.3.0)_
```bash
helm install localstack-test localstack-charts/localstack --set startServices=s3 --set ingress.enabled=true
>> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

I have seen that @kristapsstrals  on PR #26 update the ingress, but I tested it for both version `v0.3.0` and `v0.2.3` which failed.

BTW:

I am running on 
```bash
kubectl version
>> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
>> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by whummer** [comment]
Thanks for reporting @miaucl . This is largely a community-maintained repo, the LocalStack maintainers are currently not really following up on the issues created in here. Do you think you could contribute a pull request to get this fixed for both API versions? Thanks for your help! 🙏

**Comment by miaucl** [comment]
I am quite new to kubernetes and helm and just figuring stuff out as I am moving my setup from docker compose to k8s. 

I can try 😃
If I find a solution, surely I will post it!

**Comment by miaucl** [comment]
Coming back with a more specific error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http): missing required field "paths" in io.k8s.api.networking.v1.HTTPIngressRuleValue
```

I guess the problem is that the ingress `yaml` definition in the template folder is mal-formed. 

I have it almost running on my machine and will post a PR soonish.

**Comment by miaucl** [comment]
Hello
This version of the localstack helm chart is currently broken for k8s >= 1.19. There are three PRs to fix this problem as well as other bugs concerning the mounted volumes and tests.
- #31 
- #32 
- #33

**Comment by whummer** [comment]
Thanks so much for digging into these issues @miaucl ! 🙏 Changes look awesome - merged the PRs, new chart releases are currently being triggered by the CI pipeline.. Thanks for your help!

**Comment by miaucl** [comment]
Perfect, happy to help :)
