### ISSUE TITLE
Cannot deploy localstack-0.3.3

### ISSUE THREAD

**Issue by tom-mckay** [localstack/helm-charts#34]
The commits from PR #33 seem to have broken the localstack Helm chart. I'm no longer able to deploy it.

Steps to reproduce:
```
helm repo add localstack-repo https://helm.localstack.cloud
helm upgrade --kube-context kind --namespace localstack --install --wait localstack localstack-repo/localstack
```

Error received in output:
```
Release "localstack" does not exist. Installing it now.
Error: template: localstack/templates/tests/test-connection.yaml:20:63: executing "localstack/templates/tests/test-connection.yaml" at <$.Values.startServices>: invalid value; expected string
```

**Comment by whummer** [comment]
Thanks for reporting @tom-mckay - perhaps @miaucl can help out here? 🙏  Thanks

In the meantime, can you pin the chart to a previous version (e.g., by pointing your helm client to an earlier commit in this repo), is that possible?

**Comment by tom-mckay** [comment]
Yes, I was able to get around this for now by adding `--version 0.3.2` to my helm command.

I poked around at the chart changes to see what's wrong. I was able to get `helm template` to work with two changes. First, in `test-connection.yaml` I changed:
```
{{- if or (empty $.Values.startServices) (contains .name ($.Values.startServices)) -}}
```
to
```
{{- if or (empty $.Values.startServices) (contains .name ($.Values.startServices)) }}
```

Finally, I uncommented the `startServices` line in `values.yaml`, since `or` statements in golang templates do not short circuit.

I'll defer to the maintainers on whether that's the solution they want to implement here.

**Comment by miaucl** [comment]
Thanks for your solution. I just left for vacation and can only have a look at it the week after. But I agree with @whummer changes!

**Comment by miaucl** [comment]
I think instead of changing the `values.yaml` file, changing the line 
```
{{- if or (empty $.Values.startServices) (contains .name ($.Values.startServices)) -}}
```

to 

```
{{- if or (empty $.Values.startServices) (contains .name ($.Values.startServices | default "")) }}
```

solves the problem, too.

Thanks at @tom-mckay for mention that it **does not** short circuit, didn't know that :)
