### ISSUE TITLE
enableStartupScripts not mounting /docker-entrypoint-initaws.d

### ISSUE THREAD

**Issue by stephenhatch** [localstack/helm-charts#35]
When using `enableStartupScripts`, it's impossible to mount `/docker-entrypoint-initaws.d` due to the following line:
https://github.com/localstack/helm-charts/blob/7f43ab1713d84b7e3bf8296aff1b70c1241145e4/charts/localstack/templates/deployment.yaml#L55

The conditional should be updated to account for `enableStartupScripts` independently from the other configuration options.

**Comment by whummer** [comment]
Hi @stephenhatch , thanks for reporting this issue. This repo is largely maintained by the community (not by LocalStack maintainers themselves) - do you think you could contribute a pull request with a fix? Thanks for your help! 🙏
