### ISSUE TITLE
Helm chart failing when namespace is purely numeric

### ISSUE THREAD

**Issue by pguglev** [localstack/helm-charts#59]
Hello folks. I stumbled upon a strange error when installing localstack via helm. Here is the error:
`Error: unable to build kubernetes objects from release manifest: [unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 4, error found in #10 byte of ...|mespace":4444412}}|..., bigger context ...|0.4.1"},"name":"localstack-mod-test","namespace":4444412}}|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 4, error found in #10 byte of ...|mespace":4444412},"s|..., bigger context ...|0.4.1"},"name":"localstack-mod-test","namespace":4444412},"spec":{"externalTrafficPolicy":null,"port|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 4, error found in #10 byte of ...|mespace":4444412},"s|..., bigger context ...|0.4.1"},"name":"localstack-mod-test","namespace":4444412},"spec":{"replicas":1,"selector":{"matchLab|...]`

The following modification at all places, where Namespace is referenced, seems to fix the issue:
`{{ .Release.Namespace | quote }}`

So, whenever we reference the Namespace, we use the "| quote" thing.
Would this be a good fix for the issue? Is there any other way to circumvent the problem?

**Comment by whummer** [comment]
Hi @pguglev , thanks for reporting - sounds like a good solution to quote the namespace values. This repo is largely maintained by the community (not by the LocalStack core maintainers) - do you think you could create a pull request to add this functionality? Thanks for your help!

/cc Any other thoughts @LaikaN57 ?

**Comment by pguglev** [comment]
Yes, I can do that. Be warned however, that I am not an expert in the matter. But I am sure someone more experienced will review my merge request.

**Comment by whummer** [comment]
Thanks @pguglev , fixed in https://github.com/localstack/helm-charts/pull/63 👍
