### ISSUE TITLE
charts use deprecated endpoint for liveness and readiness probes

### ISSUE THREAD

**Issue by nivintw** [localstack/helm-charts#73]
From the logs of the pod:

/health is deprecated (since 1.3.0) and will be removed in upcoming releases of LocalStack! Use /_localstack/health instead.

Submitting a PR momentarily to update it.

Note:
it's hard-coded atm; would maybe be better to have this be specifiable in the values.yaml file. 
For now happy to just share the quick-patch upstream.

**Comment by nivintw** [comment]
I don't know if it'll make a difference, but I am running the localstack-pro image.

**Comment by nivintw** [comment]
https://github.com/localstack/helm-charts/pull/74

**Comment by alexrashed** [comment]
fixed with #74
