### ISSUE TITLE
/docker-entrypoint-initaws.d scripts does not appear to be running

### ISSUE THREAD

**Issue by surgiie** [localstack/helm-charts#79]
Im having a hard time trying to track down why the startup script content is not being executed on startup.

Im passing the following values to the helm chart install:

```yaml
enableStartupScripts: true
startupScriptContent: |
  awslocal sqs create-queue --queue-name my-queue
```

From what i can tell, the  config map is created:

```yaml
# kubectl describe configmap myapp-localstack-init-scripts-config 
Name:         myapp-localstack-init-scripts-config
Namespace:    default
Labels:       app.kubernetes.io/instance=myapp-localstack
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=localstack
              app.kubernetes.io/version=latest
              helm.sh/chart=localstack-0.5.5
Annotations:  meta.helm.sh/release-name: myapp-localstack
              meta.helm.sh/release-namespace: default

Data
====
myapp-localstack-init-scripts-config.sh:
----
awslocal sqs create-queue --queue-name my-queue


BinaryData
====

Events:  <none>

````

I even confirm the script is being mounted in the pod:

`kubectl exec -it deployment/myapp-localstack -- bash`

```
localstack@myapp-localstack-77486c75fc-cbn28:/opt/code/localstack$ cd /docker-entrypoint-initaws.d/
localstack@myapp-localstack-77486c75fc-cbn28:/docker-entrypoint-initaws.d$ ls -lah



total 12K
drwxrwxrwx 3 root root 4.0K Mar 28 00:43 .
drwxr-xr-x 1 root root 4.0K Mar 28 00:50 ..
drwxr-xr-x 2 root root 4.0K Mar 28 00:43 ..2023_03_28_00_43_55.1670092728
lrwxrwxrwx 1 root root   32 Mar 28 00:43 ..data -> ..2023_03_28_00_43_55.1670092728
lrwxrwxrwx 1 root root   56 Mar 28 00:43 myapp-localstack-init-scripts-config.sh -> ..data/myapp-localstack-init-scripts-config.


```

The script appears to be present and it seems to be detected to some degree as i get this warning:

```
============================================================================
  It seems you are using an init script in /docker-entrypoint-initaws.d.
  The INIT_SCRIPTS_PATH have been deprecated with v1.1.0 and will be removed in future releases
  of LocalStack. Please use /etc/localstack/init/ready.d instead.
  You can suppress this warning by setting LEGACY_INIT_DIR=1.

  See: https://github.com/localstack/localstack/issues/7257
============================================================================

```

Its just not executed on startup for some reason?

I have a another pod in the cluster that runs code that references the queue and its throwing "Queue doesnt exist" exception, when i run the awslocal create-queue command manually, it starts to work. Im unclear if im missing something or if this is a bug. 

Using the latest version of these helm charts and 1.4 localstack.

**Comment by alexrashed** [comment]
Hi @surgiie!
Maybe your script is not properly executable in the pod (potential issues could be the missing shebang script header or the indentation).
Could you exec into the pod again and try to:
- Execute the script manually.
- Print the content of the script.
Thanks!

**Comment by surgiie** [comment]
> Hi @surgiie! Maybe your script is not properly executable in the pod (potential issues could be the missing shebang script header or the indentation). Could you exec into the pod again and try to:
> 
> * Execute the script manually.
> * Print the content of the script.
>   Thanks!

:facepalm: Indeed was the missing shebang. 

Thanks! :sweat:

**Comment by abhibansal530** [comment]
@alexrashed But as per https://github.com/localstack/localstack/issues/7257, support for `docker-entrypoint-initaws.d` is removed in 2.0 release. So what's the recommended way to run startup script with latest version of localstack (using this helm chart)?

**Comment by alexrashed** [comment]
Hi @abhibansal530!
We will be upgrading this chart soon to the be compatible with the latest version of LocalStack soon.
In the meantime, you can use the generic `volumes` and `volumeMounts` to mount an init script configmap into the pod.
