### ISSUE TITLE
Localstack 2.0.2 not compatible with docker over tcp.

### ISSUE THREAD

**Issue by nilsbillo** [localstack/helm-charts#84]
From what I can find in localstack documentation DOCKER_HOST is not longer a configuration option only DOCKER_SOCK is available which is problematic with running lambda's. Since localstack will not be able to communicate over tcp to the dind container.

https://docs.localstack.cloud/references/configuration/

Not sure if a shared /var/run volume would work.

Error I get when trying to apply a lambda with mountDind.enabled=true.

WARN --- [   asgi_gw_5] l.s.a.i.docker_runtime_exe : WARNING: Docker not available in the LocalStack container but required to run Lambda functions. Please add the Docker volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. https://docs.localstack.cloud/references/lambda-provider-v2/#docker-not-available

EDIT: Not knowledgable of the localstack sourcecode. But to me it looks like DOCKER_HOST is always overwritten by the unix socket. https://github.com/localstack/localstack/blob/c70ce03c176d33885a674263bc77dc4dfa48c7f7/localstack/utils/bootstrap.py#L531

So I do not see how this env variable could achive anything?
https://github.com/localstack/helm-charts/blob/28418ad2292d22974b181b6c61b5aec00e19e22b/charts/localstack/templates/deployment.yaml#L149

**Comment by ryancurrah** [comment]
@nilsbillo why did you close this? We would like an answer this from localstack as well.
