### ISSUE TITLE
-test-connection and -test-s3 run before the localstack pod is ready

### ISSUE THREAD

**Issue by gheorghestrimtu** [localstack/helm-charts#86]
These tests try to hit the main pod before this pod is actually ready to receive requests.
These tests always fail.
Maybe it would help to use Helm test hooks with post-install,post-upgrade.

**Comment by alexrashed** [comment]
Hi @gheorghestrimtu!
Thanks for your report. Could you please give us more details?

The tests are executed successfully in our test pipeline: https://github.com/localstack/helm-charts/actions/runs/4944865679/jobs/8840824325
Also, the `test` hook is quite explicitly for the execution of tests and these tests need to be invoked explicitly using the `helm test` command: https://helm.sh/docs/topics/charts_hooks/#the-available-hooks
Maybe you should use `helm install --wait ...` and then call `helm test` in your scenario?

**Comment by gheorghestrimtu** [comment]
I am doing only `helm install` and the tests still run
